version: "2.1"

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_HOST=mysql:3306
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes: 
      - ./schema/0_initial_database.sql:/docker-entrypoint-initdb.d/0_initial_database.sql
  
  # check & test schema UP Migration 
  db_migrate_up:
    image: migrate/migrate
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./schema:/schema
    command: -verbose -path schema -database "mysql://root:password@tcp(mysql:3306)/demo_employee_migrate" up
  
  # check & test schema DOWN Migration 
  db_migrate_down:
    image: migrate/migrate
    depends_on:
      mysql:
        condition: service_healthy
      db_migrate_up:
        condition: service_completed_successfully
    volumes:
      - ./schema:/schema
    command: -verbose -path schema -database "mysql://root:password@tcp(mysql:3306)/demo_employee_migrate" down -all

  