version: "3.7"

services:
  mysql:
    image: mysql:5.7
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_HOST=mysql:3306
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demo_employee_migrate
  
  cli_migrate:
    restart: on-failure
    image: migrate/migrate
    depends_on:
      - mysql
    volumes:
      - ./schema:/schema
    command: -verbose -path /schema -database "mysql://root:password@tcp(mysql:3306)/demo_employee_migrate" up

  