name: Deploy to Dev

on:
  push:
    branches: [master]

jobs:
  deploy_to_dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Go 1.16.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
        id: go
      
      - name: Test Local Migration
        run: make test-db

      - name: Install Migrate CLI
        run: |
          go install -tags 'mysql github' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Run Migration to Dev env
        env:
          SQL_DSN: mysql://root:password@tcp(0.tcp.ngrok.io:18416)/demo_employee_migrate
        run: |
          migrate -verbose -database "${SQL_DSN}" -path schema up
      
      - name: Deploy Stack 
        run: echo "Stack is Deployed successfully!"