name: Test DB Only

on:
  push:
    branches: [master]

jobs:
  deploy_to_dev:
    name: Test DB Only
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Go 1.16.3
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3
        id: go
      
      - name: Test Local Migration
        run: make test-db
